azs:
- name: z1
- name: z2
- name: z3

vm_types:
- name: default
  cloud_properties:
    instance_type: c1-m4
    ephemeral_disk: 10_240

disk_types:
- name: default
  disk_size: 1024

networks:
- name: default
  type: manual
  subnets:
  - azs: [z1,z2,z3]
    range: 10.245.0.0/16
    dns: [8.8.8.8]
    reserved: 10.245.0.2-10.245.0.10
    gateway: 10.245.0.1
    static: 10.245.0.250-10.245.0.254
    #cloud_properties:
    #  name: bosh-network

#vm_extensions:
#- name: all_ports

compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: default
  network: default
