azs:
- name: z1
  cloud_properties:
    target: az1
- name: z2
  cloud_properties:
    target: az2

vm_types:
- name: default
  cloud_properties:
    instance_type: c2-m4
    ephemeral_disk: 10_240
- name: compilation
  cloud_properties:
    instance_type: c4-m8
    ephemeral_disk: 40_960
# Required by postgres-release, cf-deployment
- name: small
  cloud_properties:
    instance_type: c2-m4
    ephemeral_disk: 10_240
# Used by cf-deployment
- name: minimal
  cloud_properties:
    instance_type: c2-m2
    ephemeral_disk: 10_240
- name: small-highmem
  cloud_properties:
    instance_type: c2-m8
    ephemeral_disk: 10_240

disk_types:
- name: default
  disk_size: 1024
# Required by postgres-release, cf-deployment
- name: 10GB
  disk_size: 10240
# Used by cf-deployment
- disk_size: 5120
  name: 5GB
- disk_size: 100240
  name: 100GB

networks:
- name: default
  type: manual
  subnets:
  - az: z1
    range: 240.0.4.1/24
    dns: [192.168.1.1]
    reserved: 240.0.4.2-240.0.4.9
    gateway: 240.0.4.1
    static: 240.0.4.10-240.0.4.19
  - az: z2
    range: 240.0.5.1/24
    dns: [192.168.1.1]
    reserved: 240.0.5.2-240.0.5.9
    gateway: 240.0.5.1
    static: 240.0.5.10-240.0.5.19

vm_extensions:
# Used by cf-deployment
- name: 5GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 5_120
- name: 10GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 10_240
- name: 50GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 51_200
- name: 100GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 102_400
- name: 500GB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 512_000
- name: 1TB_ephemeral_disk
  cloud_properties:
    ephemeral_disk: 1_024_000
- name: diego-ssh-proxy-network-properties
- name: ssh-proxy-and-router-lb
- name: cf-router-network-properties
- name: cf-tcp-router-network-properties
- name: credhub-lb

compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: compilation
  network: default
