---
- type: replace
  path: /releases/-
  value:
    name: lxd-bosh-cpi
    url: file://((cpi_path))

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://storage.googleapis.com/bosh-core-stemcells/1.492/bosh-stemcell-1.492-openstack-kvm-ubuntu-jammy-go_agent.tgz
    sha1: 448fa6f48597c030ae5e478dd63bf11def5fea2d

# Configure LXD sizes
- type: replace
  path: /resource_pools/name=vms/cloud_properties?
  value:
    instance_type: c2-m4
    ephemeral_disk: 16_384

# Add CPI job
- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value: &cpi_job
    name: lxd_cpi
    release: lxd-bosh-cpi

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_job?
  value: lxd_cpi

- type: replace
  path: /cloud_provider/template?
  value: *cpi_job

# This is for rendering within the VM once stood up
- type: replace
  path: /instance_groups/name=bosh/properties/lxd_cpi?
  value:
    lxd:
      project_name: ((lxd_project_name))
      profile_name: ((lxd_profile_name))
      network_name: ((lxd_network_name))
      storage_pool_name: ((lxd_storage_pool_name))
      url: ((lxd_url))
      insecure_skip_verify: ((lxd_insecure))
      tls_client_cert: ((lxd_client_cert))
      tls_client_key: ((lxd_client_key))
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222
      blobstore:
        provider: dav
        options:
          endpoint: http://((internal_ip)):25250
          user: agent
          password: ((blobstore_agent_password))

# This is for initial standup of VM (bootstrap?)
- type: replace
  path: /cloud_provider/properties/lxd_cpi?
  value:
    lxd:
      project_name: ((lxd_project_name))
      profile_name: ((lxd_profile_name))
      network_name: ((lxd_network_name))
      storage_pool_name: ((lxd_storage_pool_name))
      url: ((lxd_url))
      insecure_skip_verify: ((lxd_insecure))
      tls_client_cert: ((lxd_client_cert))
      tls_client_key: ((lxd_client_key))
    agent:
      mbus: "https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868"
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
