---
- type: replace
  path: /releases/-
  value:
    name: lxd-bosh-cpi
    url: file://((cpi_path))

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-xenial-go_agent?v=170.14
    sha1: 9190e1d20dcb937e007abbb4054e19b1daa8d0a4

# Configure LXD sizes
- type: replace
  path: /resource_pools/name=vms/cloud_properties?
  value:
    instance_type: c2-m4

# Add CPI job
- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value: &cpi_job
    name: lxd_cpi
    release: lxd-bosh-cpi

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_job?
  value: lxd_cpi

- type: replace
  path: /cloud_provider/template?
  value: *cpi_job

# This is for rendering within the VM once stood up
- type: replace
  path: /instance_groups/name=bosh/properties/lxd_cpi?
  value:
    lxd:
      unix_socket: ((lxd_unix_socket))
      project_name: ((lxd_project_name))
      profile_name: ((lxd_profile_name))
      network_name: ((lxd_network_name))
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222
      blobstore:
        provider: dav
        options:
          endpoint: http://((internal_ip)):25250
          user: agent
          password: ((blobstore_agent_password))

# This is for initial standup of VM (bootstrap?)
- type: replace
  path: /cloud_provider/properties/lxd_cpi?
  value:
    lxd:
      unix_socket: ((lxd_unix_socket))
      project_name: ((lxd_project_name))
      profile_name: ((lxd_profile_name))
      network_name: ((lxd_network_name))
    agent:
      mbus: "https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868"
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
