---
- type: replace
  path: /releases/-
  value:
    name: lxd-bosh-cpi
    url: file://((cpi_path))

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-xenial-go_agent?v=170.14
    sha1: 9190e1d20dcb937e007abbb4054e19b1daa8d0a4

# Add CPI job
- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value: &cpi_job
    name: lxd_cpi
    release: lxd-bosh-cpi

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_job?
  value: lxd_cpi

- type: replace
  path: /cloud_provider/template?
  value: *cpi_job

- type: replace
  path: /cloud_provider/properties/lxd_cpi?
  value:
    lxd:
      unix_socket: ((lxd_unix_socket))

#- type: replace
#  path: /instance_groups/name=bosh/properties/lxd_cpi?
#  value:
#    lxd:
#      unix_socket: ((lxd_unix_socket))
