---
- type: replace
  path: /releases/-
  value:
    name: lxd-bosh-cpi
    url: file://((cpi_path))

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-openstack-kvm-ubuntu-jammy-go_agent?v=1.506
    sha1: aeecfaf2b62c9ae8190c7e8539e816257c8f944d

# Configure LXD sizes
- type: replace
  path: /resource_pools/name=vms/cloud_properties?
  value:
    instance_type: c2-m4
    ephemeral_disk: 16_384

# Add CPI job
- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value: &cpi_job
    name: lxd_cpi
    release: lxd-bosh-cpi

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_job?
  value: lxd_cpi

- type: replace
  path: /cloud_provider/template?
  value: *cpi_job

# This is for rendering within the VM once stood up
- type: replace
  path: /instance_groups/name=bosh/properties/lxd_cpi?
  value:
    lxd: &lxd_settings
      project_name: ((lxd_project_name))
      profile_name: ((lxd_profile_name))
      network_name: ((lxd_network_name))
      storage_pool_name: ((lxd_storage_pool_name))
      url: ((lxd_url))
      insecure_skip_verify: ((lxd_insecure))
      tls_client_cert: ((lxd_client_cert))
      tls_client_key: ((lxd_client_key))
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222
    #   blobstore:
    #     provider: dav
    #     options:
    #       endpoint: http://((internal_ip)):25250
    #       user: agent
    #       password: ((blobstore_agent_password))
    agent_config: &agent_config_settings
      type: CDROM
      label: "config-2"
      metadata_path: "ec2/latest/meta-data.json"
      userdata_path: "ec2/latest/user-data"
      filestore_path: "/var/vcap/store/agent-data"

# This is for initial standup of VM (bootstrap?)
- type: replace
  path: /cloud_provider/properties/lxd_cpi?
  value:
    lxd: *lxd_settings
    agent:
      mbus: "https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868"
    #   blobstore:
    #     provider: local
    #     options:
    #       blobstore_path: /var/vcap/micro_bosh/data/cache
    agent_config: 
      <<: *agent_config_settings
      filestore_path: "/tmp"
