---
- type: replace
  path: /releases/-
  value:
    name: lxd-bosh-cpi
    url: file://((cpi_path))

- type: replace
  path: /resource_pools/name=vms/stemcell?
  value:
    url: https://bosh.io/d/stemcells/bosh-warden-boshlite-ubuntu-xenial-go_agent?v=170.21
    sha1: 0bd5f1458c065246840e4498d7c66cdb9335f908

# Configure LXD sizes
- type: replace
  path: /resource_pools/name=vms/cloud_properties?
  value:
    instance_type: c2-m4
    ephemeral_disk: 16_384
    devices:
      lxdsocket:
        type: proxy
        connect: unix:((lxd_unix_socket))
        listen: unix:/warden-cpi-dev/lxd.socket
        bind: container
        uid: "1000"   # vcap
        gid: "1000"   # vcap
        mode: "0660"
    # This configuration is required by all Bosh Agents and should be on the LXD profile.
    # They are left here as a sample and a referene.
    config:
      security.privileged: "true"
      raw.lxc: |
        lxc.apparmor.profile = unconfined

# Add CPI job
- type: replace
  path: /instance_groups/name=bosh/jobs/-
  value: &cpi_job
    name: lxd_cpi
    release: lxd-bosh-cpi

- type: replace
  path: /instance_groups/name=bosh/properties/director/cpi_job?
  value: lxd_cpi

- type: replace
  path: /cloud_provider/template?
  value: *cpi_job

# This is for rendering within the VM once stood up
- type: replace
  path: /instance_groups/name=bosh/properties/lxd_cpi?
  value:
    lxd:
      project_name: ((lxd_project_name))
      profile_name: ((lxd_profile_name))
      network_name: ((lxd_network_name))
      storage_pool_name: ((lxd_storage_pool_name))
      unix_socket: /warden-cpi-dev/lxd.socket
    agent:
      mbus: nats://nats:((nats_password))@((internal_ip)):4222
      blobstore:
        provider: dav
        options:
          endpoint: http://((internal_ip)):25250
          user: agent
          password: ((blobstore_agent_password))

# This is for initial standup of VM (bootstrap?)
- type: replace
  path: /cloud_provider/properties/lxd_cpi?
  value:
    lxd:
      project_name: ((lxd_project_name))
      profile_name: ((lxd_profile_name))
      network_name: ((lxd_network_name))
      storage_pool_name: ((lxd_storage_pool_name))
      unix_socket: ((lxd_unix_socket))
    agent:
      mbus: "https://mbus:((mbus_bootstrap_password))@0.0.0.0:6868"
      blobstore:
        provider: local
        options:
          blobstore_path: /var/vcap/micro_bosh/data/cache
