# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Go

on:
  push:
    branches: [ "main" ]
    paths:
    - 'src/**'
    - '.github/workflows/go.yml'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'src/**'
    - '.github/workflows/go.yml'

defaults:
  run:
    working-directory: src

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'src/go.mod'

    - name: Build
      run: go build -mod vendor -v ./...

    - name: Test
      run: go test -mod vendor -v ./...
